### ISSUE TITLE
Attribute is missing!

### ISSUE THREAD

**Issue by youssef962** [ShiQiu0419/BAAF-Net#8]
when I run the data_prepare_s3dis it gives me the following error:
```
File "E:\Research\Codes\BAAF-Net\BAAF-Net-main\helper_tool.py", line 215, in grid_sub_sampling
    return cpp_subsampling.compute(points, features=features, classes=labels, sampleDl=grid_size,
AttributeError: module 'cpp_wrappers.cpp_subsampling.grid_subsampling' has no attribute 'compute'
```

so the compute attribute is missing, what can I do?!

**Comment by ShiQiu0419** [comment]
Hi @youssef962 ,

I suppose that you did not compile the cuda operations correctly. please run "sh compile_op.sh" again to see wthether there is any errors.

**Comment by youssef962** [comment]
it says a g++ command is not found !
```
youss@DESKTOP-CVS0PDM MINGW64 ~
$ /e/Research/Codes/BAAF-Net/BAAF-Net-main/utils/sampling/compile_ops.sh
2021-07-28 16:49:17.674398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-28 16:49:17.674450: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-07-28 16:49:20.536507: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-28 16:49:20.536559: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/e/Research/Codes/BAAF-Net/BAAF-Net-main/utils/sampling/compile_ops.sh: line 8: /usr/local/cuda-10.0/bin/nvcc: No such file or directory
/e/Research/Codes/BAAF-Net/BAAF-Net-main/utils/sampling/compile_ops.sh: line 9: g++: command not found
```

**Comment by youssef962** [comment]
I did but it shows this error:
```
E:\Research\Codes\S3DISdataset\Stanford3dDataset_v1.2_Aligned_Version\Area_1/conferenceRoom_1/Annotations
Traceback (most recent call last):
  File "data_prepare_s3dis.py", line 80, in <module>
    convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name))
  File "data_prepare_s3dis.py", line 57, in convert_pc2ply
    sub_xyz, sub_colors, sub_labels = DP.grid_sub_sampling(xyz, colors, labels, sub_grid_size)
  File "E:\Research\Codes\BAAF-Net\BAAF-Net-main\helper_tool.py", line 215, in grid_sub_sampling
    return cpp_subsamplingcompute(points, features=features, classes=labels, sampleDl=grid_size,
NameError: name 'cpp_subsamplingcompute' is not defined
```
